// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://rhirqpgkzoapuofvlvbo.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJoaXJxcGdrem9hcHVvZnZsdmJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMzODMxNTMsImV4cCI6MjA0ODk1OTE1M30.NLVSe2UXSGhDCq85YR7_Xlu9JhPmw0kAZ8u7BF619BQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);